import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Damazon%26oq%3Damazon%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDI4MDVqMGoyqAIAsAIB%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3DgiEqaI6JDcy4seMPzaTYCA&q=EhAkAUkAc-fAAHF42JYqgMsTGILDqMEGIjB2g4ys2MEAYWEN5PwhQHppfm8tGP83FiIeaHZaWfEBmDhLFekx7zVDc7EhoKhIR3MyAVJaAUM');
  await page.locator('iframe[name="a-r3zg0pt6yn18"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('.rc-imageselect-tile').first().click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('.rc-imageselect-tile').first().click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(4) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(4) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(4) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(4)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(4) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(4) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().locator('tr:nth-child(4) > td:nth-child(4)').click();
  await page.locator('iframe[name="c-r3zg0pt6yn18"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('#tads').getByRole('link', { name: 'Shop online at Amazon India' }).click();
  await page.getByRole('link', { name: 'Mobiles' }).click();
  await page.getByRole('link', { name: 'Bestsellers' }).click();
  await page.getByRole('link', { name: 'Mobiles' }).click();
  await page.getByRole('link', { name: 'Bestsellers' }).click();
  await page.getByRole('link', { name: 'Mobiles' }).click();
  await page.locator('#sobe_d_b_ms_21_CW_1').getByRole('link', { name: 'heroalt1' }).click();
  await page.goto('https://www.amazon.in/dp/B0F7LL5ZXX/ref=QAHzEditorial_en_IN_1?pf_rd_r=F3F5E9C4B1BA432E88CF&pf_rd_p=b762e821-d8fb-4f3e-8549-e6aca468c292&pf_rd_m=A1VBAL9TL5WCBF&pf_rd_s=merchandised-search-21_CW&pf_rd_t=&pf_rd_i=1389401031&th=1');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'dead Silicone+TPU Back Cover' }).click();
  const page1 = await page1Promise;
  await page1.goto('https://www.amazon.in/dp/B0DTQBGYFB/ref=sspa_dk_detail_2?pd_rd_i=B0DTQBGYFB&pd_rd_w=L4SZp&content-id=amzn1.sym.9f1cb690-f0b7-44de-b6ff-1bad1e37d3f0&pf_rd_p=9f1cb690-f0b7-44de-b6ff-1bad1e37d3f0&pf_rd_r=P013QQKVM3KV7FVXWGY4&pd_rd_wg=evRs8&pd_rd_r=e6c0aad7-b339-43b1-9eec-9310ec8aae70&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&th=1');
  await page1.getByRole('link', { name: 'Mobiles', exact: true }).click();
  await page1.getByRole('link', { name: 'OP 13R', exact: true }).click();
  await page1.goto('https://www.amazon.in/dp/B0DPS62DYH/?_encoding=UTF8&ref_=cct_cg_Budget_2c1&pf_rd_p=acc38935-279e-41f9-ab48-534d85cfef1e&pf_rd_r=XW8NH9JD12NFFEQHZS1F&th=1');
  await page1.getByRole('button', { name: 'Add to Cart', exact: true }).click();
  await page1.getByRole('button', { name: 'Cart', exact: true }).click();
  await page1.getByRole('button', { name: 'Proceed to Buy Buy Amazon' }).click();
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).fill('itsranveerkumar@gmail.com');
  await page1.getByRole('button', { name: 'Continue' }).click();
  await page1.getByRole('button', { name: 'Proceed to create an account' }).click();
  await page1.goto('https://www.amazon.in/ap/signin?openid.pape.max_auth_age=900&openid.return_to=https%3A%2F%2Fwww.amazon.in%2Fcheckout%2Fentry%2Fcart%3FisEligibilityLogicDisabled%3D1%26referrer%3Dcart%26ref_%3Dox_sc_proceed%26proceedToCheckout%3D1%26oldCustomerId%3D0%26tangoWeblabStatus%3Dtango_enable_unrec_customer%26pipelineType%3DChewbacca%26isToBeGiftWrappedBefore%3D0%26isUnrec%3D1&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amazon_checkout_in&openid.mode=checkid_setup&language=en_IN&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0');
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).click();
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).press('ArrowRight');
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).press('ArrowRight');
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).press('ArrowRight');
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).press('ArrowRight');
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).press('ArrowRight');
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).press('ArrowRight');
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).press('ArrowRight');
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).press('ArrowRight');
  await page1.locator('#claim-input-clear-button').click();
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).fill('7543981278');
  await page1.locator('#claim-input-dropdown span').nth(1).click();
  await page1.getByText('India +').click();
  await page1.getByRole('button', { name: 'Continue' }).click();
  await page1.getByRole('textbox', { name: 'Password' }).fill('Ranv2001@');
  await page1.getByRole('button', { name: 'Sign in' }).click();
  await page1.getByRole('link', { name: 'Change' }).click();
  await page1.locator('#claim-input-clear-button').click();
  await page1.getByRole('textbox', { name: 'Enter your mobile number or' }).fill('itzranveerkumar@gmail.com');
  await page1.getByRole('button', { name: 'Continue' }).click();
  await page1.getByRole('button', { name: 'Proceed to create an account' }).click();
  await page1.getByRole('textbox', { name: 'Mobile number' }).fill('7543981278');
  await page1.getByRole('textbox', { name: 'Your name' }).click();
  await page1.getByRole('textbox', { name: 'Your name' }).fill('Ranveer Kumar');
  await page1.getByRole('textbox', { name: 'Password (at least 6' }).click();
  await page1.getByRole('textbox', { name: 'Password (at least 6' }).fill('Ranv2001@');
  await page1.getByRole('button', { name: 'Verify mobile number' }).click();
  await page1.locator('label i').click();
  await page1.getByRole('button', { name: 'Create your Amazon account' }).click();
  await page1.getByRole('textbox', { name: 'Enter OTP' }).fill('932005');
  await page1.getByRole('button', { name: 'Verify OTP Button' }).click();
  await page1.getByRole('link', { name: 'Add a new delivery address' }).click();
  await page1.getByRole('textbox', { name: 'Full name (First and Last' }).click();
  await page1.getByRole('textbox', { name: 'Full name (First and Last' }).fill('Ranveer Kumar');
  await page1.getByRole('textbox', { name: 'Mobile number' }).click();
  await page1.getByRole('textbox', { name: 'Mobile number' }).fill('7543981278');
  await page1.getByRole('textbox', { name: 'Pincode' }).click();
  await page1.getByRole('textbox', { name: 'Pincode' }).fill('201201');
  await page1.getByRole('textbox', { name: 'Flat, House no., Building,' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Flat, House no., Building,' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Flat, House no., Building,' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Pincode' }).click();
  await page1.getByRole('textbox', { name: 'Pincode' }).fill('201301');
  await page1.getByRole('textbox', { name: 'Flat, House no., Building,' }).click();
  await page1.getByRole('textbox', { name: 'Flat, House no., Building,' }).fill('N 185 Noida sector 12');
  await page1.getByRole('textbox', { name: 'Area, Street, Sector, Village' }).click();
  await page1.getByRole('textbox', { name: 'Area, Street, Sector, Village' }).fill('Noida Sector 12');
  await page1.getByRole('textbox', { name: 'Landmark' }).click();
  await page1.getByRole('textbox', { name: 'Landmark' }).fill('near by Noida Stadium');
  await page1.getByRole('checkbox', { name: 'Make this my default address' }).check();
  await page1.getByTestId('bottom-continue-button').click();
  await page1.goto('https://www.amazon.in/checkout/p/p-404-8771427-3789136/pay?pipelineType=Chewbacca&hasWorkingJavascript=1');
  await page1.getByLabel('Other UPI Apps').getByLabel('').check();
  await page1.getByRole('textbox', { name: 'Enter UPI ID' }).click();
  await page1.getByRole('textbox', { name: 'Enter UPI ID' }).fill('xyz@apl');
  await page1.getByRole('textbox', { name: 'Enter UPI ID' }).press('Enter');
  await page1.getByRole('button', { name: 'Verify' }).click();
  await page1.getByTestId('secondary-continue-button').click();
  await page1.locator('#bottomSubmitOrderButtonId').getByTestId('SPC_selectPlaceOrder').click();
  await page1.goto('https://pay.amazon.in/process-payment?clientId=AmazonRetail%3AChewbacca&purchaseId=404-8771427-3789136&callbackUrl=https%3A%2F%2Fwww.amazon.in%2Fgp%2Fbuy%2Fthankyou%2Fhandlers%2Fdisplay.html%3FapxRedirectionsComplete%3D1%26ref_%3Dchk_typ_mfa%26purchaseId%3D404-8771427-3789136');
});await page1.goto('https://www.amazon.in/cpe/revisepayments?orderId=406-0717545-8125151&ref_=payment_reject_or_cancel');
